#!/bin/bash -e
#
ORG_PATH="github.com/royvandewater"
REPO_PATH="${ORG_PATH}/go-to-hell"
CHALLENGES=$(cat ./submissions.txt)

if [ -z "$CHALLENGES" ]; then
	echo "Please put a newline seperated list of challenges in submissions.txt"
	echo "See README.md for details"
	exit 1
fi

# split CHALLENGES into an array and prepend REPO_PATH to each local package
split=(${CHALLENGES// / })
CHALLENGE_PATHS=${split[@]/#/${REPO_PATH}/}

echo "Running tests..."
go test $CHALLENGE_PATHS

echo "Checking gofmt..."
fmtRes=$(gofmt -s -l $CHALLENGES)
if [ -n "${fmtRes}" ]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 255
fi

echo "Checking golint..."
lintRes=$(golint $CHALLENGES)
if [ -n "${lintRes}" ]; then
	echo -e "golint checking failed:\n${lintRes}"
	exit 255
fi

echo "Checking govet..."
vetRes=$(go vet $CHALLENGE_PATHS)
if [ -n "${vetRes}" ]; then
	echo -e "govet checking failed:\n${vetRes}"
	exit 255
fi

echo "Success"
